<a href="https://colab.research.google.com/github/SHermukhammadjon/Mohirdev_Data_Science_praktikum/blob/main/ML/scikit_learn2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Maschine Learning Loyiha qadamalri
(2-notebook)

<img src="https://drive.google.com/uc?id=1ZKgMJ92OMgfBHsvQmFmNhXw5aM9P9vXu">

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn 

<img src='https://drive.google.com/uc?id=1fwgyerWq4kaJJBGMQOPr4UKzqXmCmYF6'>

# 3-QADAM. MLga tayyorgarlik. NaN qiymatlar.
###13.05.2023

In [44]:
def load_dataset(URL):
  return pd.read_csv(URL)

In [45]:
dataset = load_dataset("https://github.com/ageron/handson-ml2/blob/master/datasets/housing/housing.csv?raw=true")
dataset.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [46]:
from sklearn.model_selection import train_test_split 
train_set, test_set = train_test_split(dataset, test_size = 0.2, random_state = 31)

In [47]:
housing = train_set.drop('median_house_value', axis = 1)
housing_lables = train_set['median_house_value'].copy() 

In [48]:
housing 

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
7083     -118.01     33.93                31.0       3395.0           742.0   
747      -122.09     37.66                40.0       1340.0           313.0   
19922    -119.35     36.32                10.0       3817.0           719.0   
449      -122.28     37.87                46.0       1777.0           446.0   
11808    -121.11     38.91                24.0       2558.0           423.0   
...          ...       ...                 ...          ...             ...   
604      -122.08     37.69                36.0       2350.0           499.0   
28       -122.28     37.84                50.0       2082.0           492.0   
826      -122.09     37.63                36.0       1570.0           274.0   
3735     -118.40     34.19                35.0       1631.0           356.0   
14946    -116.98     32.72                15.0       4209.0           680.0   

       population  households  median_income ocean_proximity  
7083       1886.0       737.0         4.4118       <1H OCEAN  
747         766.0       271.0         3.4722        NEAR BAY  
19922      1686.0       714.0         3.8235          INLAND  
449         805.0       431.0         2.8676        NEAR BAY  
11808      1149.0       403.0         4.0679          INLAND  
...           ...         ...            ...             ...  
604        1105.0       467.0         3.3021        NEAR BAY  
28         1131.0       473.0         1.6424        NEAR BAY  
826         992.0       249.0         5.3644        NEAR BAY  
3735        862.0       368.0         3.6007       <1H OCEAN  
14946      1914.0       641.0         4.5135       <1H OCEAN  

[16512 rows x 9 columns]

In [50]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16512 entries, 7083 to 14946
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           16512 non-null  float64
 1   latitude            16512 non-null  float64
 2   housing_median_age  16512 non-null  float64
 3   total_rooms         16512 non-null  float64
 4   total_bedrooms      16347 non-null  float64
 5   population          16512 non-null  float64
 6   households          16512 non-null  float64
 7   median_income       16512 non-null  float64
 8   ocean_proximity     16512 non-null  object 
dtypes: float64(8), object(1)
memory usage: 1.3+ MB


In [51]:
# 1 Qatorlarni tashlab yuborish
housing.dropna(subset = ['total_bedrooms'])

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
7083     -118.01     33.93                31.0       3395.0           742.0   
747      -122.09     37.66                40.0       1340.0           313.0   
19922    -119.35     36.32                10.0       3817.0           719.0   
449      -122.28     37.87                46.0       1777.0           446.0   
11808    -121.11     38.91                24.0       2558.0           423.0   
...          ...       ...                 ...          ...             ...   
604      -122.08     37.69                36.0       2350.0           499.0   
28       -122.28     37.84                50.0       2082.0           492.0   
826      -122.09     37.63                36.0       1570.0           274.0   
3735     -118.40     34.19                35.0       1631.0           356.0   
14946    -116.98     32.72                15.0       4209.0           680.0   

       population  households  median_income ocean_proximity  
7083       1886.0       737.0         4.4118       <1H OCEAN  
747         766.0       271.0         3.4722        NEAR BAY  
19922      1686.0       714.0         3.8235          INLAND  
449         805.0       431.0         2.8676        NEAR BAY  
11808      1149.0       403.0         4.0679          INLAND  
...           ...         ...            ...             ...  
604        1105.0       467.0         3.3021        NEAR BAY  
28         1131.0       473.0         1.6424        NEAR BAY  
826         992.0       249.0         5.3644        NEAR BAY  
3735        862.0       368.0         3.6007       <1H OCEAN  
14946      1914.0       641.0         4.5135       <1H OCEAN  

[16347 rows x 9 columns]

In [52]:
median = housing['total_bedrooms'].median()
median 

433.0

In [53]:
housing['total_bedrooms'].fillna(median)

7083     742.0
747      313.0
19922    719.0
449      446.0
11808    423.0
         ...  
604      499.0
28       492.0
826      274.0
3735     356.0
14946    680.0
Name: total_bedrooms, Length: 16512, dtype: float64

In [54]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16512 entries, 7083 to 14946
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           16512 non-null  float64
 1   latitude            16512 non-null  float64
 2   housing_median_age  16512 non-null  float64
 3   total_rooms         16512 non-null  float64
 4   total_bedrooms      16347 non-null  float64
 5   population          16512 non-null  float64
 6   households          16512 non-null  float64
 7   median_income       16512 non-null  float64
 8   ocean_proximity     16512 non-null  object 
dtypes: float64(8), object(1)
memory usage: 1.3+ MB


# 3-QADAM. MLga tayyorgarlik. NaN qiymatlarni almashtirish
### 13.05.2023

#### SimpleImputer

In [55]:
from sklearn.impute import SimpleImputer 

In [56]:
imputer = SimpleImputer(strategy = 'median')

In [14]:
housing_num = housing.drop('ocean_proximity', axis = 1)
housing_num 

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
7083     -118.01     33.93                31.0       3395.0           742.0   
747      -122.09     37.66                40.0       1340.0           313.0   
19922    -119.35     36.32                10.0       3817.0           719.0   
449      -122.28     37.87                46.0       1777.0           446.0   
11808    -121.11     38.91                24.0       2558.0           423.0   
...          ...       ...                 ...          ...             ...   
604      -122.08     37.69                36.0       2350.0           499.0   
28       -122.28     37.84                50.0       2082.0           492.0   
826      -122.09     37.63                36.0       1570.0           274.0   
3735     -118.40     34.19                35.0       1631.0           356.0   
14946    -116.98     32.72                15.0       4209.0           680.0   

       population  households  median_income  
7083       1886.0       737.0         4.4118  
747         766.0       271.0         3.4722  
19922      1686.0       714.0         3.8235  
449         805.0       431.0         2.8676  
11808      1149.0       403.0         4.0679  
...           ...         ...            ...  
604        1105.0       467.0         3.3021  
28         1131.0       473.0         1.6424  
826         992.0       249.0         5.3644  
3735        862.0       368.0         3.6007  
14946      1914.0       641.0         4.5135  

[16512 rows x 8 columns]

In [15]:
imputer.fit(housing_num)

SimpleImputer(strategy='median')

In [16]:
imputer.statistics_  # Calculated each column median value 

array([-118.5   ,   34.26  ,   29.    , 2127.    ,  433.    , 1166.    ,
        408.    ,    3.5394])

In [17]:
X = imputer.transform(housing_num)  # replace median values intenc NaN value
X

array([[-118.01  ,   33.93  ,   31.    , ..., 1886.    ,  737.    ,
           4.4118],
       [-122.09  ,   37.66  ,   40.    , ...,  766.    ,  271.    ,
           3.4722],
       [-119.35  ,   36.32  ,   10.    , ..., 1686.    ,  714.    ,
           3.8235],
       ...,
       [-122.09  ,   37.63  ,   36.    , ...,  992.    ,  249.    ,
           5.3644],
       [-118.4   ,   34.19  ,   35.    , ...,  862.    ,  368.    ,
           3.6007],
       [-116.98  ,   32.72  ,   15.    , ..., 1914.    ,  641.    ,
           4.5135]])

In [18]:
type(X)

numpy.ndarray

In [19]:
imputer.fit_transform(housing_num)

array([[-118.01  ,   33.93  ,   31.    , ..., 1886.    ,  737.    ,
           4.4118],
       [-122.09  ,   37.66  ,   40.    , ...,  766.    ,  271.    ,
           3.4722],
       [-119.35  ,   36.32  ,   10.    , ..., 1686.    ,  714.    ,
           3.8235],
       ...,
       [-122.09  ,   37.63  ,   36.    , ...,  992.    ,  249.    ,
           5.3644],
       [-118.4   ,   34.19  ,   35.    , ...,  862.    ,  368.    ,
           3.6007],
       [-116.98  ,   32.72  ,   15.    , ..., 1914.    ,  641.    ,
           4.5135]])

In [20]:
housing_tr = pd.DataFrame(X, columns = housing_num.columns, index = housing_num.index)
housing_tr

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
7083     -118.01     33.93                31.0       3395.0           742.0   
747      -122.09     37.66                40.0       1340.0           313.0   
19922    -119.35     36.32                10.0       3817.0           719.0   
449      -122.28     37.87                46.0       1777.0           446.0   
11808    -121.11     38.91                24.0       2558.0           423.0   
...          ...       ...                 ...          ...             ...   
604      -122.08     37.69                36.0       2350.0           499.0   
28       -122.28     37.84                50.0       2082.0           492.0   
826      -122.09     37.63                36.0       1570.0           274.0   
3735     -118.40     34.19                35.0       1631.0           356.0   
14946    -116.98     32.72                15.0       4209.0           680.0   

       population  households  median_income  
7083       1886.0       737.0         4.4118  
747         766.0       271.0         3.4722  
19922      1686.0       714.0         3.8235  
449         805.0       431.0         2.8676  
11808      1149.0       403.0         4.0679  
...           ...         ...            ...  
604        1105.0       467.0         3.3021  
28         1131.0       473.0         1.6424  
826         992.0       249.0         5.3644  
3735        862.0       368.0         3.6007  
14946      1914.0       641.0         4.5135  

[16512 rows x 8 columns]

# 3-QADAM. MLga tayyorgarlik. Matnlar. SimpleEncoder
### 2023.05.23

In [21]:
housing_cat = housing[['ocean_proximity']]
housing_cat 

ocean_proximity
7083        <1H OCEAN
747          NEAR BAY
19922          INLAND
449          NEAR BAY
11808          INLAND
...               ...
604          NEAR BAY
28           NEAR BAY
826          NEAR BAY
3735        <1H OCEAN
14946       <1H OCEAN

[16512 rows x 1 columns]

In [57]:
housing_cat.value_counts()

ocean_proximity
<1H OCEAN          7318
INLAND             5225
NEAR OCEAN         2107
NEAR BAY           1857
ISLAND                5
dtype: int64

In [58]:
from sklearn.preprocessing import OrdinalEncoder 

In [59]:
encoder = OrdinalEncoder()

In [61]:
housing_cat_encoder = encoder.fit_transform(housing_cat)
housing_cat_encoder[:10]

array([[0.],
       [3.],
       [1.],
       [3.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [3.]])

#3-QADAM. MLga tayyorgarlik. Matnlar. OneHotEncoder
### 2023.05.23

In [62]:
from sklearn.preprocessing import OneHotEncoder

In [63]:
cat_encoder = OneHotEncoder()

In [64]:
housing_cat1hot = cat_encoder.fit_transform(housing_cat)
housing_cat1hot.toarray() 

array([[1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       ...,
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [65]:
housing_cat.value_counts()

ocean_proximity
<1H OCEAN          7318
INLAND             5225
NEAR OCEAN         2107
NEAR BAY           1857
ISLAND                5
dtype: int64

In [66]:
pd.get_dummies(housing_cat['ocean_proximity'])

<1H OCEAN  INLAND  ISLAND  NEAR BAY  NEAR OCEAN
7083           1       0       0         0           0
747            0       0       0         1           0
19922          0       1       0         0           0
449            0       0       0         1           0
11808          0       1       0         0           0
...          ...     ...     ...       ...         ...
604            0       0       0         1           0
28             0       0       0         1           0
826            0       0       0         1           0
3735           1       0       0         0           0
14946          1       0       0         0           0

[16512 rows x 5 columns]

# 3-QADAM. MLga tayyorgarlik. Transformer yasaymiz.
### 2023.05.24

In [67]:
from sklearn.base import BaseEstimator, TransformerMixin

In [68]:
# we should columns indexs 
rooms_ix, bedrooms_ix, population_ix, households_ix = 3, 4, 5, 6

In [69]:
class CombineAttributesAdder(BaseEstimator, TransformerMixin):
  def __init__(self, add_bedrooms_per_room = False):
    self.add_bedrooms_per_room = add_bedrooms_per_room
  
  def fit(self, X, y = None):
    return self
  
  def transform(self, X):
    rooms_per_household = X[:, rooms_ix] / X[:, households_ix]
    population_per_household = X[:, population_ix] / X[:, households_ix]
    if self.add_bedrooms_per_room:
      bedrooms_per_room = X[:, bedrooms_ix] / X[:, rooms_ix]
      return np.c_[X, rooms_per_household, population_per_household, bedrooms_per_room]
    else:
      return np.c_[X, rooms_per_household, population_per_household]

In [84]:
print(housing.values[0, :])

[-118.01 33.93 31.0 3395.0 742.0 1886.0 737.0 4.4118 '<1H OCEAN']


In [85]:
combine = CombineAttributesAdder(add_bedrooms_per_room = True)
print(combine.transform(housing.values)[0, :])

[-118.01 33.93 31.0 3395.0 742.0 1886.0 737.0 4.4118 '<1H OCEAN'
 4.606512890094979 2.559023066485753 0.21855670103092784]


# 3-QADAM. MLga tayyorgarlik. Normalizasiya (MinMaxScaler)
### 2023.05.24

In [86]:
housing 

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
7083     -118.01     33.93                31.0       3395.0           742.0   
747      -122.09     37.66                40.0       1340.0           313.0   
19922    -119.35     36.32                10.0       3817.0           719.0   
449      -122.28     37.87                46.0       1777.0           446.0   
11808    -121.11     38.91                24.0       2558.0           423.0   
...          ...       ...                 ...          ...             ...   
604      -122.08     37.69                36.0       2350.0           499.0   
28       -122.28     37.84                50.0       2082.0           492.0   
826      -122.09     37.63                36.0       1570.0           274.0   
3735     -118.40     34.19                35.0       1631.0           356.0   
14946    -116.98     32.72                15.0       4209.0           680.0   

       population  households  median_income ocean_proximity  
7083       1886.0       737.0         4.4118       <1H OCEAN  
747         766.0       271.0         3.4722        NEAR BAY  
19922      1686.0       714.0         3.8235          INLAND  
449         805.0       431.0         2.8676        NEAR BAY  
11808      1149.0       403.0         4.0679          INLAND  
...           ...         ...            ...             ...  
604        1105.0       467.0         3.3021        NEAR BAY  
28         1131.0       473.0         1.6424        NEAR BAY  
826         992.0       249.0         5.3644        NEAR BAY  
3735        862.0       368.0         3.6007       <1H OCEAN  
14946      1914.0       641.0         4.5135       <1H OCEAN  

[16512 rows x 9 columns]

In [87]:
housing.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  16512.000000  16512.000000        16512.000000  16512.000000   
mean    -119.567325     35.628352           28.656734   2636.864220   
std        2.000261      2.135195           12.627148   2194.580225   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1446.000000   
50%     -118.500000     34.260000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.470000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  
count    16347.000000  16512.000000  16512.000000   16512.000000  
mean       537.933933   1425.368702    499.572250       3.876215  
std        422.981140   1141.720172    383.384752       1.899114  
min          1.000000      6.000000      1.000000       0.499900  
25%        295.000000    788.000000    279.000000       2.566300  
50%        433.000000   1166.000000    408.000000       3.539400  
75%        648.000000   1730.000000    606.000000       4.760100  
max       6445.000000  35682.000000   6082.000000      15.000100

<img src='https://drive.google.com/uc?id=1z7XC3bp7VSZNWAH3gmh8i6BuaSaL-6Hm'>

In [97]:
median_income_scaled = (housing['median_income'] - housing['median_income'].min()) / (housing['median_income'].max() - housing['median_income'].min())
median_income_scaled

7083     0.269782
747      0.204983
19922    0.229211
449      0.163287
11808    0.246066
           ...   
604      0.193253
28       0.078792
826      0.335478
3735     0.213845
14946    0.276796
Name: median_income, Length: 16512, dtype: float64

In [98]:
median_income_scaled.describe()

count    16512.000000
mean         0.232846
std          0.130972
min          0.000000
25%          0.142508
50%          0.209618
75%          0.293803
max          1.000000
Name: median_income, dtype: float64

In [95]:
from sklearn.preprocessing import MinMaxScaler 

In [96]:
min_max_scaler = MinMaxScaler()
min_max_scaler.fit_transform(housing_num)

array([[0.6417004 , 0.1477152 , 0.58823529, ..., 0.05269649, 0.12103272,
        0.26978249],
       [0.22874494, 0.54410202, 0.76470588, ..., 0.02130284, 0.04440059,
        0.20498338],
       [0.50607287, 0.40170032, 0.17647059, ..., 0.04709048, 0.11725045,
        0.22921063],
       ...,
       [0.22874494, 0.54091392, 0.68627451, ..., 0.02763763, 0.04078277,
        0.33547813],
       [0.60222672, 0.17534538, 0.66666667, ..., 0.02399372, 0.06035192,
        0.21384533],
       [0.74595142, 0.01912859, 0.2745098 , ..., 0.05348133, 0.10524585,
        0.27679618]])

In [99]:
housing_num

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
7083     -118.01     33.93                31.0       3395.0           742.0   
747      -122.09     37.66                40.0       1340.0           313.0   
19922    -119.35     36.32                10.0       3817.0           719.0   
449      -122.28     37.87                46.0       1777.0           446.0   
11808    -121.11     38.91                24.0       2558.0           423.0   
...          ...       ...                 ...          ...             ...   
604      -122.08     37.69                36.0       2350.0           499.0   
28       -122.28     37.84                50.0       2082.0           492.0   
826      -122.09     37.63                36.0       1570.0           274.0   
3735     -118.40     34.19                35.0       1631.0           356.0   
14946    -116.98     32.72                15.0       4209.0           680.0   

       population  households  median_income  
7083       1886.0       737.0         4.4118  
747         766.0       271.0         3.4722  
19922      1686.0       714.0         3.8235  
449         805.0       431.0         2.8676  
11808      1149.0       403.0         4.0679  
...           ...         ...            ...  
604        1105.0       467.0         3.3021  
28         1131.0       473.0         1.6424  
826         992.0       249.0         5.3644  
3735        862.0       368.0         3.6007  
14946      1914.0       641.0         4.5135  

[16512 rows x 8 columns]

# 3-QADAM. MLga tayyorgarlik. Standartizasiya (StandardScaler)
### 2023.05.24
<img src='https://drive.google.com/uc?id=1cGfTObRgXtW3BZ3MRcr4MP_ZLtgIQq_a' width="300" height="150">

In [100]:
from sklearn.preprocessing import StandardScaler

In [101]:
standart_scaler = StandardScaler()
standart_scaler.fit_transform(housing_num)

array([[ 0.77858458, -0.79543244,  0.18557923, ...,  0.40346598,
         0.61931242,  0.28202705],
       [-1.26121131,  0.95153334,  0.89835081, ..., -0.57753965,
        -0.59621352, -0.21274505],
       [ 0.10865162,  0.32393705, -1.47755446, ...,  0.2282864 ,
         0.55931865, -0.02775842],
       ...,
       [-1.26121131,  0.93748267,  0.58156344, ..., -0.37958673,
        -0.65359886,  0.78364466],
       [ 0.58360409, -0.67366003,  0.5023666 , ..., -0.49345345,
        -0.34319632, -0.14507985],
       [ 1.29353305, -1.36214252, -1.08157025, ...,  0.42799112,
         0.36890364,  0.33557997]])