<a href="https://colab.research.google.com/github/SHermukhammadjon/Mohirdev_Data_Science_praktikum/blob/main/8_14_logical_conditons.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ![Imgur](https://i.imgur.com/5pXzCIu.png)
#\#8.14 Mantiqiy shart operatorlari

In [10]:
import numpy as np

## Masala: 
### Bizta 2ta malumot (massivlar) bor : x_arr ava y_arr. Va ushbu arraylarni
### uzunligi bilan teng condition_array True va False qiymatlaridan iborat massivimiz bor 
### agarshar True bo'ls  x_arr elementlarni False bo'lsa y_arr elementlarni qabul qiluvchi yangi massiv xosil qiling

In [25]:
x_arr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
y_arr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [26]:
#conditon
cond = np.array([True, False, True, True, False])
cond

array([ True, False,  True,  True, False])

## where funksyasi

In [30]:
# where
result = np.where(cond, x_arr, y_arr) #agar shara cond massivda True bolsa x arrayn fals bo'lsa y arrayni mos elementlarni olib yang numpy array qaytaradi
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [32]:
arr = np.random.randn(4, 4) #4 ga 4 o'lchamli taxminiy elementlar
arr 

array([[ 1.07066044, -0.5396034 ,  0.2731266 , -2.05044122],
       [-0.61677516, -1.28329387,  0.87395302, -2.30983641],
       [-0.29097327,  0.49640213, -0.07262849, -0.45520755],
       [ 0.13328128,  0.56856816,  1.15643492,  0.74592602]])

In [36]:
#where
resolts = np.where(arr<0, -2, 2) # arrayning manfiy elementlarni -2 ga musbaltarni esa 2ga almashtrish
resolts

array([[ 2, -2,  2, -2],
       [-2, -2,  2, -2],
       [-2,  2, -2, -2],
       [ 2,  2,  2,  2]])

In [39]:
np.where(arr<0, 0, arr)

array([[1.07066044, 0.        , 0.2731266 , 0.        ],
       [0.        , 0.        , 0.87395302, 0.        ],
       [0.        , 0.49640213, 0.        , 0.        ],
       [0.13328128, 0.56856816, 1.15643492, 0.74592602]])