<a href="https://colab.research.google.com/github/SHermukhammadjon/Mohirdev_Data_Science_praktikum/blob/main/matematik_va_statistik_ammallar16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ![Imgur](https://i.imgur.com/5pXzCIu.png)
#\#8.15 Matematik va statistik amallar

In [1]:
import numpy as np

## Statistik metodlar
<img src='https://drive.google.com/uc?id=1H0HMoW5_xT5IuowjtpTjGD9JGLAbDTDY'>

In [25]:
# data
arr = np.random.randn(5, 4) # 5ga 4 o'lchamli taxminy elementlardan tashkil topgan array
arr

array([[-0.35271207,  0.03354282,  1.24614883,  0.18188206],
       [-2.47567823, -0.43683808, -0.21133212,  0.58962136],
       [-1.38473099,  0.5150724 ,  0.00350982, -0.26911913],
       [ 1.92068018,  0.91802588, -0.54112696, -0.97963381],
       [-1.43171176, -0.40174143, -0.54067727,  0.24116031]])

## ***Sum*** metodi

In [26]:
arr.sum() # arrayning barcha elementlarni yig'ndsini qaytaradi

-3.3756582010309044

In [27]:
np.sum(arr)

-3.3756582010309044

In [28]:
arr.sum(axis=1) # axis 1 bo'ycha harbir listni elementlarni yigndsi

array([ 1.10886163, -2.53422708, -1.13526789,  1.31794528, -2.13297015])

In [29]:
arr.sum(axis=0) # ustun bo'ycha yig'ndi

array([-3.72415287,  0.6280616 , -0.04347771, -0.23608922])

## ***mean*** metodi

In [30]:
# sodda ma'lumot
data = np.arange(5) # 0->5gacha tashkil topgan array
data

array([0, 1, 2, 3, 4])

In [31]:
mean = np.sum(data)/len(data)
mean

2.0

In [32]:
# Numpy mean
np.mean(data)


2.0

In [33]:
data.mean()

2.0

In [35]:
arr

array([[-0.35271207,  0.03354282,  1.24614883,  0.18188206],
       [-2.47567823, -0.43683808, -0.21133212,  0.58962136],
       [-1.38473099,  0.5150724 ,  0.00350982, -0.26911913],
       [ 1.92068018,  0.91802588, -0.54112696, -0.97963381],
       [-1.43171176, -0.40174143, -0.54067727,  0.24116031]])

In [37]:
arr.mean() # arrayning barcha o'rtacha  elementlarni qiymati 

-0.16878291005154522

In [39]:
np.mean(arr, axis=1) #Qator bo'ycha o'rtacha qiymatni qaytaradi

array([ 0.27721541, -0.63355677, -0.28381697,  0.32948632, -0.53324254])

In [40]:
np.mean(arr, axis = 0) #Ustunlar bo'ycha o'rtacha qiymatni qaytaradi

array([-0.74483057,  0.12561232, -0.00869554, -0.04721784])

## ***cumsum*** metodi

In [42]:
data

array([0, 1, 2, 3, 4])

In [44]:
data.cumsum() # o'zidan oldin kelgan barcha elementlarni qo'shadi

array([ 0,  1,  3,  6, 10])