<a href="https://colab.research.google.com/github/SHermukhammadjon/Mohirdev_Data_Science_praktikum/blob/main/NumPy_finaly_practice8-25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini 
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [1]:
import numpy as np
np

<module 'numpy' from '/usr/local/lib/python3.8/dist-packages/numpy/__init__.py'>

In [ ]:
np.__version__

'1.22.4'

In [ ]:
np.show_config()

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring! 

`💡Ishora` numpy.array

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
arr1

array([1, 2, 3, 4, 5, 6, 7])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [ ]:
arr2 = np.zeros((9, 1, 1, 1, 1, 1, 1, 1, 1))
arr2

array([[[[[[[[[0.]]]]]]]],







       [[[[[[[[0.]]]]]]]],







       [[[[[[[[0.]]]]]]]],







       [[[[[[[[0.]]]]]]]],







       [[[[[[[[0.]]]]]]]],







       [[[[[[[[0.]]]]]]]],







       [[[[[[[[0.]]]]]]]],







       [[[[[[[[0.]]]]]]]],







       [[[[[[[[0.]]]]]]]]])

In [ ]:
arr2.ndim

9

In [ ]:
arr2.shape

(9, 1, 1, 1, 1, 1, 1, 1, 1)

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [ ]:
arr3 = np.arange(20)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18,  3])

In [ ]:
arr3.size

20

In [ ]:
arr3.itemsize

8

In [ ]:
a = np.array("12345")
a.itemsize

20

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin? 


`💡Ishora` np.info

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [ ]:
arr4 = np.zeros((12, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1))
arr4[-1] = 1
arr4

array([[[[[[[[[[[[0.],
                 [0.],
                 [0.]]]]]]]]]]],










       [[[[[[[[[[[0.],
                 [0.],
                 [0.]]]]]]]]]]],










       [[[[[[[[[[[0.],
                 [0.],
                 [0.]]]]]]]]]]],










       [[[[[[[[[[[0.],
                 [0.],
                 [0.]]]]]]]]]]],










       [[[[[[[[[[[0.],
                 [0.],
                 [0.]]]]]]]]]]],










       [[[[[[[[[[[0.],
                 [0.],
                 [0.]]]]]]]]]]],










       [[[[[[[[[[[0.],
                 [0.],
                 [0.]]]]]]]]]]],










       [[[[[[[[[[[0.],
                 [0.],
                 [0.]]]]]]]]]]],










       [[[[[[[[[[[0.],
                 [0.],
                 [0.]]]]]]]]]]],










       [[[[[[[[[[[0.],
                 [0.],
                 [0.]]]]]]]]]]],










       [[[[[[[[[[[0.],
                 [0.],
                 [0.]]]]]]]]]]],










       [[[[[[[[[[[1.]

In [ ]:
arr4.ndim 

12

In [ ]:
arr4[11]

array([[[[[[[[[[[1.],
                [1.],
                [1.]]]]]]]]]]])

In [ ]:
arr4[11][0][0][0][0][0][0][0][0][0][0][0]

1.0

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [ ]:
arr5 = np.arange(20, 59)
arr5

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58])

#### 8. Vektor yarating va uni teskari o'zgartiring 
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [ ]:
arr6 = np.arange(20, 59)
arr6

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58])

In [ ]:
arr6 = arr6[::-1]
arr6

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [ ]:
arr7 = np.arange(12, 21)
arr7.reshape(3, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0] 





`💡Ishora` np.nonzero

In [ ]:
arr8 = np.array([3, 7, 0, 0, 9, 0])
arr8.nonzero()

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [ ]:
arr9 = np.random.random((2, 2, 2))
arr9

array([[[0.98092039, 0.83948824],
        [0.57810331, 0.58956864]],

       [[0.44706477, 0.17486051],
        [0.91325019, 0.27353199]]])

In [ ]:
arr9.ndim

3

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [ ]:
arr10 = np.random.random((9, 9))
arr10

array([[0.90679453, 0.13487861, 0.47527604, 0.48774652, 0.25889395,
        0.21434383, 0.80288018, 0.26160123, 0.30175507],
       [0.79771458, 0.04346707, 0.33231274, 0.87256274, 0.10265581,
        0.75875048, 0.3182462 , 0.69687175, 0.1579175 ],
       [0.71060292, 0.65914249, 0.37144406, 0.46969669, 0.1896354 ,
        0.81514861, 0.27817292, 0.50388874, 0.15616507],
       [0.78839903, 0.6191495 , 0.24704499, 0.27765187, 0.82645446,
        0.87827275, 0.04198713, 0.6298117 , 0.3197005 ],
       [0.13044357, 0.81198511, 0.00993993, 0.44806241, 0.33978346,
        0.66613198, 0.22452503, 0.89625337, 0.1131663 ],
       [0.65273041, 0.27816594, 0.15951598, 0.96509284, 0.19589063,
        0.06448047, 0.67523951, 0.41361391, 0.3579297 ],
       [0.67357761, 0.03833371, 0.21110902, 0.89203949, 0.58338599,
        0.99305793, 0.42045011, 0.33996071, 0.04692796],
       [0.08133432, 0.13080302, 0.02026745, 0.94298803, 0.46547851,
        0.46263897, 0.30891932, 0.36131425, 0.30443698],


In [ ]:
arr10.shape

(9, 9)

In [ ]:
arr10.min() #The smallest value

0.009939925414455764

In [ ]:
arr10.max() #The bigest value 

0.9930579265905426

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [ ]:
0 * np.nan

nan

In [ ]:
np.nan == np.nan

False

In [ ]:
np.inf > np.nan

False

In [ ]:
np.nan - np.nan

nan

In [ ]:
np.nan in set([np.nan])

True

In [ ]:
0.7 == 7 * 0.1

False

In [ ]:
7 * 0.1

0.7000000000000001

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [ ]:
arr11 = np.ones([6, 3])
arr11

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr12 = np.ones([3, 4])
arr12 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr13 = np.dot(arr11, arr12)
arr13

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
sum(range(5), -1)

9

In [ ]:
sum(range(5))

10

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
from numpy import *

In [ ]:
sum(range(5), -1)

10

In [ ]:
sum(range(5))

10

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b 
[False False]
a >= b 
[False False] 
a < b 
[ True True] 
a <= b 
[ True True]
```

In [ ]:
a = np.array([1, 2])
b = np.array([4, 5])

In [ ]:
a

array([1, 2])

In [ ]:
b

array([4, 5])

In [ ]:
a > b

array([False, False])

In [ ]:
a >= b

array([False, False])

In [ ]:
a < b

array([ True,  True])

In [ ]:
a <= b

array([ True,  True])

#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0)

array(0)

In [ ]:
np.array(0) / np.array(0)

<ipython-input-204-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


nan

In [ ]:
np.array(0) // np.array(0)

<ipython-input-205-4764261090d0>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [ ]:
np.array([np.nan])

array([nan])

In [ ]:
np.array([np.nan]).astype(int)

array([-9223372036854775808])

In [ ]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [ ]:
arr1 = np.array([1, 1, 1, 2, 3, 3, 3, 3, 4, 4])
arr1

array([1, 1, 1, 2, 3, 3, 3, 3, 4, 4])

In [ ]:
arr2 = np.array([1, 3, 10, 11, 12, 13])
arr2

array([ 1,  3, 10, 11, 12, 13])

In [ ]:
np.intersect1d(arr1, arr2)

array([1, 3])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [ ]:
arr = np.random.randn(10)
arr

array([ 0.21532898, -0.20621154, -0.05244675, -0.43072105, -0.00911224,
       -0.84192494,  1.43943501,  0.80542618, -1.65771519,  0.07808573])

In [ ]:
arr.astype(int)

array([ 0,  0,  0,  0,  0,  0,  1,  0, -1,  0])

In [ ]:
np.trunc(arr)

array([ 0., -0., -0., -0., -0., -0.,  1.,  0., -1.,  0.])

In [ ]:
np.floor(arr)

array([ 0., -1., -1., -1., -1., -1.,  1.,  0., -2.,  0.])

In [ ]:
arr - arr % 1 

array([ 0., -1., -1., -1., -1., -1.,  1.,  0., -2.,  0.])

#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [ ]:
arr = np.arange(0, 3)
np.array([arr, arr, arr])

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
np.array([arr, arr, arr]).shape 

(3, 3)

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [ ]:
arr = np.random.randn(10)
arr

array([ 1.24351609, -0.03959992,  0.02598997,  0.68507366, -0.512127  ,
       -1.9528914 ,  0.5183842 , -0.13454805,  0.13390126,  1.38870847])

In [ ]:
arr.sort()

In [ ]:
arr

array([-1.9528914 , -0.512127  , -0.13454805, -0.03959992,  0.02598997,
        0.13390126,  0.5183842 ,  0.68507366,  1.24351609,  1.38870847])

#### 22. A va B nomi bilan ikkita tasodifiy qiymatlardan iborat bo'lgan massiv yarating, so'ng ulardan qaysi biri katta yoki kichik ekanligini tekshiring.

`💡Ishora` np.allclose, np.array_equal

In [ ]:
A = np.random.randn(10)
A

array([-0.24507097,  0.3151373 , -0.18329359, -0.6409283 ,  0.28600668,
        1.01438482, -0.02810891, -2.43498498, -0.87189563,  0.84492608])

In [ ]:
B = np.random.randn(10)
B

array([-2.09735606, -0.97641525,  0.12467569,  1.35762237,  0.39888769,
        0.20145197,  1.01436508,  0.77242275,  1.14363413, -0.52808618])

In [ ]:
A.sum()

-1.94382750001368

In [ ]:
B.sum()

1.411202179921068

In [ ]:
np.allclose(A, B) # if both vale's sum equal : True else: False 

False

In [ ]:
np.array_equal(A, B)

False

In [ ]:
np.allclose(1, 0.99999999)

True

In [ ]:
np.allclose(1, 0.999)

False

In [ ]:
np.array_equal(5, 5)

True

In [ ]:
np.array_equal(5, 4.9999999999)

False

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring. 


`💡Ishora` np.dot or np.ones

In [ ]:
arr1 = np.arange(6*3).reshape(6, 3)
arr1 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
arr2 = np.arange(3*4).reshape(3, 4)
arr2 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.dot(arr1, arr2)

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218],
       [164, 203, 242, 281],
       [200, 248, 296, 344]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [15]:
arr1 = np.random.randn(5)
arr1

array([ 0.37124216, -1.14799111, -1.04842159,  0.48696599,  1.08577132])

In [16]:
arr1.shape

(5,)

In [17]:
arr1[np.argmax(arr1)] = 0  #berilgan arrayni eng katta qiymatini indexsni qaytaradi
arr1

array([ 0.37124216, -1.14799111, -1.04842159,  0.48696599,  0.        ])

#### 25. Quyidagi dastur qanday natija beradi?
```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [21]:
sum(range(5), -1)

9

In [22]:
list(range(5))

[0, 1, 2, 3, 4]

In [23]:
sum(range(5))

10

In [30]:
from numpy import *
sum(range(5), -1)

10

#### 26. NumPy kutubxonasi yordamida ikkita massivni solishtiruvchi dastur tuzing.
```python
Array a: [1 2]
Array b: [4 5]
a > b 
[False False]
a >= b 
[False False] 
a < b 
[ True True] 
a <= b 
[ True True]
```

In [39]:
arr1 = [1, 2]
arr1

[1, 2]

In [40]:
arr2 = [4, 5]
arr2

[4, 5]

In [46]:
arr1 > arr2

False

In [47]:
arr1 >= arr2

False

In [48]:
arr1 < arr2

True

In [49]:
arr1 <= arr2

True

#### 27. Ikkita umumiy qiymatlari mavjud bo'lgan massiv yarating, so'ng ulardagi umumiy qiymatlarni aniqlovchi dastur tuzing.


`💡Ishora` np.intersect1d

In [53]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr2 = np.arange(7, 17)
arr2

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [55]:
np.intersect1d(arr1, arr2)

array([7, 8, 9])

#### 28. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [89]:
today = np.datetime64('today')
today

numpy.datetime64('2023-03-06')

In [90]:
today + np.timedelta64(1)

numpy.datetime64('2023-03-07')

In [91]:
np.timedelta64(2)

numpy.timedelta64(2)

In [92]:
def time_detect():
  print(f"today: {np.datetime64('today')}")
  print(f"tomorow: {np.datetime64('today') + np.timedelta64(1)}")


In [93]:
time_detect()

today: 2023-03-06
tomorow: 2023-03-07


#### 29. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [121]:
start = np.datetime64('2016-01-01')
start

numpy.datetime64('2016-01-01')

In [122]:
stop = np.datetime64('2016-02-01')
stop

numpy.datetime64('2016-02-01')

In [124]:
np.arange(start, stop)

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

#### 30. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`



---

####with floor:

In [236]:
arr1 = np.random.randn(10)
arr1 

array([ 2.1140256 ,  0.96306241,  1.23017057, -0.96734153, -2.90647216,
       -0.8903522 ,  1.05782652,  0.40093631,  0.21630892, -0.28518505])

In [237]:
np.floor(arr1)

array([ 2.,  0.,  1., -1., -3., -1.,  1.,  0.,  0., -1.])

In [238]:
conditon = np.floor(arr1) < 0
conditon

array([False, False, False,  True,  True,  True, False, False, False,
        True])

In [239]:
arr1[conditon] = 0 - arr1[conditon]

In [240]:
arr1 

array([2.1140256 , 0.96306241, 1.23017057, 0.96734153, 2.90647216,
       0.8903522 , 1.05782652, 0.40093631, 0.21630892, 0.28518505])



---

####with %:

In [242]:
arr1 = np.random.randn(10)
arr1 

array([-0.30402647, -1.1186573 , -0.7891445 ,  0.0121387 , -0.12691319,
        1.14559703, -0.20206723,  0.78443966,  2.77766059,  0.41378745])



---

####with np.trunc:

In [243]:
arr1 = np.random.randn(10)
arr1 

array([-0.15806331,  1.97390451,  1.55050524,  2.41992171, -1.31908986,
       -0.21622386,  0.86458291, -1.60266944,  0.61670877, -0.7265437 ])

In [245]:
arr1[arr1 < 0] = 0 - arr1[arr1 < 0] 

In [247]:
arr1 

array([0.15806331, 1.97390451, 1.55050524, 2.41992171, 1.31908986,
       0.21622386, 0.86458291, 1.60266944, 0.61670877, 0.7265437 ])

In [246]:
np.trunc(arr1)

array([0., 1., 1., 2., 1., 0., 0., 1., 0., 0.])



---

####with astype:

In [248]:
arr1 = np.random.randn(10)
arr1 

array([-1.57080051, -1.13772664, -0.19774707, -0.65701634,  0.56184321,
       -1.41440885,  0.73074419,  1.12168667, -0.3710875 ,  1.02537499])

In [250]:
arr1.astype(np.uinit8)

AttributeError: ignored

#### 31. Qator qiymatlari 0 dan 2 gacha bo'lgan 3x3 matritsa yarating.


`💡Ishora` np.arange

#### 32. Tasodifiy qiymatlardan tashkil topgan 10 o'lchovli vektor yarating, so'ng uning qiymatlarini o'sish tartibida yozing.


`💡Ishora` sort

#### 33. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

#### 34. Tasodifiy qiymatlardan tashkil topgan 5 o'lchovli vektor yarating, so'ng uning eng katta qiymatini 0 raqamiga almashtiring.


`💡Ishora` argmax

#### 35. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

#### 36. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? 


`💡Ishora` stride_tricks.as_strided

#### 37. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`