<a href="https://colab.research.google.com/github/SHermukhammadjon/Mohirdev_Data_Science_praktikum/blob/main/sorting17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ![Imgur](https://i.imgur.com/5pXzCIu.png)
#\#8.15 Tartiblash (Sorting)

In [2]:
import numpy as np

In [4]:
#data
arr = np.random.rand(4)
arr

array([0.55384413, 0.74991928, 0.153533  , 0.07188263])

## ***sort*** funksyasi

In [8]:
# 1-usul
sorted_arr = np.sort(arr)  #arrni tartiblangan varyanti o'sish tartibda
sorted_arr 

array([0.07188263, 0.153533  , 0.55384413, 0.74991928])

In [10]:
# 2-usul
arr.sort() # arrayni o'zni tartiblash
arr

array([0.07188263, 0.153533  , 0.55384413, 0.74991928])

In [11]:
# Teskari tartiblash
revers_arr = -np.sort(-arr) #teskari tartibdagi array
revers_arr

array([0.74991928, 0.55384413, 0.153533  , 0.07188263])

In [12]:
# 2D array larda tartiblash
arr2d = np.random.randn(2, 4) # (2, 4) o'lchamli massiv
arr2d

array([[ 1.86166191, -1.0628036 ,  0.47131572,  0.15516778],
       [-0.54343825,  0.83104217, -1.63812452,  1.57688203]])

In [16]:
# axis = 0 --> Qator
row_srt = np.sort(arr2d, axis=0) # qatorlari bo'ycha tartiblash
row_srt

array([[-0.54343825, -1.0628036 , -1.63812452,  0.15516778],
       [ 1.86166191,  0.83104217,  0.47131572,  1.57688203]])

In [18]:
# axis = 1 --> Ustun
col_srt = np.sort(arr2d, axis=1) # Ustun bo'ycha tartiblash
col_srt

array([[-1.0628036 ,  0.15516778,  0.47131572,  1.86166191],
       [-1.63812452, -0.54343825,  0.83104217,  1.57688203]])