<a href="https://colab.research.google.com/github/SHermukhammadjon/Mohirdev_Data_Science_praktikum/blob/main/index_and_cut.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ![Imgur](https://i.imgur.com/5pXzCIu.png)
#\#8.8 Inekslash va Kseish

In [2]:
import numpy as np

In [10]:
arr = np.arange(10, 100, 10)
arr[-2]

80

In [12]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [11]:
arr[3:5]

array([40, 50])

In [15]:
sliced_arr = arr[3:5]
sliced_arr[:] = 0
sliced_arr

array([0, 0])

In [16]:
arr

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

# asil arrayning qiymatlariga tasir qilmaslik uchun ***copy*** usuli:

In [18]:
arr1 = np.arange(10, 100, 10)
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [19]:
sliced_arr1 = arr1[3:5].copy()
sliced_arr1[:] = 0
sliced_arr1

array([0, 0])

In [20]:
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

## 2 o'lchamli (2D array) massivlarda indekslash va kesib olish
<img src = 'https://drive.google.com/uc?id=1DcoT2Dw9cWEw6cXaRc9PGOSXWQJPRsCc'>

In [30]:
arr2d = np.array([[1,2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr2d.ndim 

2

In [32]:
arr2d.shape

(3, 3)

In [38]:
arr2d[2, 2]

9

## 2 o'lchamli masivlarning birnechta elemntlarni kesib olish

In [45]:
sl_arr2d = arr2d[1:3, :]
sl_arr2d

array([[4, 5, 6],
       [7, 8, 9]])

##3 o'lchamli masivlarning birnechta elemntlarni kesib olish

In [48]:
arr3d = np.array([[[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]], 
                  
                  [[10, 11, 12],
                   [13, 14, 15],
                   [16, 17, 18]],
                  
                  [[19, 20, 21],
                  [22, 23, 24],
                  [25, 26, 27]]])

arr3d 

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [49]:
arr3d.shape 

(3, 3, 3)

In [50]:
arr3d.ndim

3

In [55]:
arr3d[0][1, 1]

5

In [57]:
arr3d[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [60]:
arr3d[2]

array([[19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])