<a href="https://colab.research.google.com/github/SHermukhammadjon/Mohirdev_Data_Science_praktikum/blob/main/NumPy/lesson9/Boolen_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ![Imgur](https://i.imgur.com/5pXzCIu.png)
#\#8.9 Boolen Indekslash

In [ ]:
import numpy as np

In [ ]:
# Names
names = np.array(['Hasan', 'Husan', 'Mirzabek', 'Eliyor', 'Husan', 'Javohir', 'Elyor'])
names 

array(['Hasan', 'Husan', 'Mirzabek', 'Eliyor', 'Husan', 'Javohir',
       'Elyor'], dtype='<U8')

In [ ]:
# data
data = np.random.randn(7, 4)
data

array([[ 0.22774024, -0.52538032,  1.29370588, -1.44939186],
       [-0.9606766 ,  1.15412137,  1.13095992,  0.72052436],
       [ 0.38801841,  0.25756965, -1.54714528, -0.33565941],
       [ 1.2444704 , -1.0639033 , -0.46154527, -0.34253584],
       [ 0.85633228,  2.06317809, -1.18795069, -2.50848049],
       [-0.45341714,  1.0229531 ,  0.48998246, -0.30288869],
       [-0.23037936, -0.98629285,  0.72612536,  1.62208579]])

In [ ]:
names == 'Husan'

array([False,  True, False, False,  True, False, False])

In [ ]:
data[names == 'Husan']  # Husanga tegishli barcha ma'lumotlarni ajratib olish

array([[0.46843864, 0.75428028, 0.16095116, 0.8053179 ],
       [0.55556903, 0.69958229, 0.38313171, 0.80725761]])

In [ ]:
data[names == 'Eliyor']  # Eliyor tegishli barcha ma'lumotlarni ajratib olish

array([[0.9323085 , 0.68913447, 0.67000096, 0.35065415]])

In [ ]:
data[names == 'Husan', 2:] # Hasanga tegishli oxirgi ustudagit 2ta istunni ajratib olish

array([[0.16095116, 0.8053179 ],
       [0.38313171, 0.80725761]])

In [ ]:
data[names != 'Husan', 2:] #Husanda tashqari hamma odamlarning ma'umotlari

array([[0.29080096, 0.45814313],
       [0.63540178, 0.34074485],
       [0.76357986, 0.48787945],
       [0.98024487, 0.89821955],
       [0.9819636 , 0.73016724]])

In [ ]:
data[~(names == 'Husan')] # yuqoridagi cell bilan bir xil natijani beradi

array([[0.71711391, 0.76126307, 0.29080096, 0.45814313],
       [0.1132639 , 0.07892818, 0.63540178, 0.34074485],
       [0.08006617, 0.52855225, 0.76357986, 0.48787945],
       [0.20578582, 0.13888541, 0.98024487, 0.89821955],
       [0.01444612, 0.37829796, 0.9819636 , 0.73016724]])

## \#vazifa
## Datadan araydan 2 ta ismmi ma'lumotlarni ajratib oling

In [ ]:
print(names)
print(data)

['Hasan' 'Husan' 'Mirzabek' 'Eliyor' 'Husan' 'Javohir' 'Elyor']
[[0.71711391 0.76126307 0.29080096 0.45814313]
 [0.24570515 0.45938023 0.55147155 0.90741936]
 [0.1132639  0.07892818 0.63540178 0.34074485]
 [0.08006617 0.52855225 0.76357986 0.48787945]
 [0.47734707 0.38807453 0.38325857 0.65479627]
 [0.20578582 0.13888541 0.98024487 0.89821955]
 [0.01444612 0.37829796 0.9819636  0.73016724]]


In [ ]:
mask = (names == 'Hasan') | (names == 'Husan')  # or ==  | == yoki
mask

array([ True,  True, False, False,  True, False, False])

In [ ]:
data[mask]

array([[0.71711391, 0.76126307, 0.29080096, 0.45814313],
       [0.24570515, 0.45938023, 0.55147155, 0.90741936],
       [0.47734707, 0.38807453, 0.38325857, 0.65479627]])

In [ ]:
print(data[data < 0])
data[data < 0] = 0

[-0.52538032 -1.44939186 -0.9606766  -1.54714528 -0.33565941 -1.0639033
 -0.46154527 -0.34253584 -1.18795069 -2.50848049 -0.45341714 -0.30288869
 -0.23037936 -0.98629285]


In [ ]:
data

array([[0.22774024, 0.        , 1.29370588, 0.        ],
       [0.        , 1.15412137, 1.13095992, 0.72052436],
       [0.38801841, 0.25756965, 0.        , 0.        ],
       [1.2444704 , 0.        , 0.        , 0.        ],
       [0.85633228, 2.06317809, 0.        , 0.        ],
       [0.        , 1.0229531 , 0.48998246, 0.        ],
       [0.        , 0.        , 0.72612536, 1.62208579]])