<a href="https://colab.research.google.com/github/SHermukhammadjon/Mohirdev_Data_Science_praktikum/blob/main/linere_algebr20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ![Imgur](https://i.imgur.com/5pXzCIu.png)
#\#8.20 CHiziqli algebra 

In [2]:
import numpy as np

In [9]:
x = np.array([[1., 2., 3.,], [4., 5., 6]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [10]:
y = np.array([[5., 5., 5.,], [4., 4., 4.]])
y

array([[5., 5., 5.],
       [4., 4., 4.]])

In [11]:
x+y

array([[ 6.,  7.,  8.],
       [ 8.,  9., 10.]])

In [12]:
y-x

array([[ 4.,  3.,  2.],
       [ 0., -1., -2.]])

In [15]:
x*5 #skalyar ko'paytmasi yani bitta soni matritsani harbir elementiga ko'paytrib chiqish


array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [16]:
x = np.array([[1., 2., 3.,], [4., 5., 6]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [17]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [20]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [21]:
y.dot(x)

array([[ 98., 127., 156.],
       [ 27.,  33.,  39.],
       [ 44.,  61.,  78.]])

In [22]:
# Liner Algebra
from numpy.linalg import inv