<a href="https://colab.research.google.com/github/SHermukhammadjon/Mohirdev_Data_Science_praktikum/blob/main/Transposing_and_Swapping11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ![Imgur](https://i.imgur.com/5pXzCIu.png)
#\#8.11 Array o'qlarini almashtirish

In [1]:
import numpy as np 

## Massivlarning positsiyasini ko'chirish ***Tanspose*** va o'qlar o'rnini almashtirish ***Swapping axes***.

### Massivning ustun va qatorlari o'rnini almashtiri jarayon  Transpose deyladi.

<img src='https://drive.google.com/uc?id=150sBCzXJgwsBXYhnPFVG4odnuJ2GnEf-'>

## ***reshape*** metodi:

In [11]:
A = np.arange(12)
A 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
A = np.arange(12).reshape(3, 4)
A 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### ***Trasnpose:***

In [13]:
A.T # A massivning Transpose ko'rinishini beradi

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## ***Swapping axes*** usluli yordamda massivning o'qlarni almashtrish

In [18]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
A.swapaxes(1, 0) #Ther is sawaping indiex 0 and 1 

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## ***Transpose***ning ishlatilshga misollar: A*A^T

In [22]:
A = np.arange(9).reshape(3, 3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
A.T 

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [24]:
np.dot(A, A.T)

array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]])

In [25]:
np.random.randn(10)

array([-0.03001818,  1.36846717, -0.42666696, -1.04532661, -0.3750973 ,
        1.08288433,  0.17027733, -0.24105425, -0.46854767,  0.77114961])