<a href="https://colab.research.google.com/github/SHermukhammadjon/Mohirdev_Data_Science_praktikum/blob/main/sorting17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ![Imgur](https://i.imgur.com/5pXzCIu.png)
# \#8.17 Tartiblash (Sorting)

In [1]:
import numpy as np

In [2]:
#data
arr = np.random.rand(4)
arr

array([0.01444621, 0.17876907, 0.87109045, 0.33931818])

## ***sort*** funksyasi

In [5]:
# 1-usul
sorted_arr = np.sort(arr)  #arrni tartiblangan varyanti o'sish tartibda
sorted_arr 

array([0.01444621, 0.17876907, 0.33931818, 0.87109045])

In [6]:
# 2-usul
arr.sort() # arrayni o'zni tartiblash
arr

array([0.01444621, 0.17876907, 0.33931818, 0.87109045])

In [9]:
# Teskari tartiblash
revers_arr = -np.sort(-arr) #teskari tartibdagi array
revers_arr

array([0.87109045, 0.33931818, 0.17876907, 0.01444621])

In [10]:
# 2D array larda tartiblash
arr2d = np.random.randn(2, 4) # (2, 4) o'lchamli massiv
arr2d

array([[-0.49197872, -1.35710148, -0.22914286,  0.23908904],
       [-0.919714  , -0.59438438,  1.29855289,  1.10240002]])

In [11]:
# axis = 0 --> Qator
row_srt = np.sort(arr2d, axis=0) # qatorlari bo'ycha tartiblash
row_srt

array([[-0.919714  , -1.35710148, -0.22914286,  0.23908904],
       [-0.49197872, -0.59438438,  1.29855289,  1.10240002]])

In [12]:
# axis = 1 --> Ustun
col_srt = np.sort(arr2d, axis=1) # Ustun bo'ycha tartiblash
col_srt 

array([[-1.35710148, -0.49197872, -0.22914286,  0.23908904],
       [-0.919714  , -0.59438438,  1.10240002,  1.29855289]])