<a href="https://colab.research.google.com/github/SHermukhammadjon/Mohirdev_Data_Science_praktikum/blob/main/8_14_logical_conditons.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ![Imgur](https://i.imgur.com/5pXzCIu.png)
# \#8.14 Mantiqiy shart operatorlari

In [1]:
import numpy as np

#### Masala: 
##### Bizta 2ta malumot (massivlar) bor : x_arr ava y_arr. Va ushbu arraylarni
##### uzunligi bilan teng condition_array True va False qiymatlaridan iborat massivimiz bor 
##### agar shart True bo'ls  x_arr elementlarni False bo'lsa y_arr elementlarni qabul qiluvchi yangi massiv xosil qiling

In [2]:
x_arr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
y_arr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [3]:
#conditon
cond = np.array([True, False, True, True, False])
cond

array([ True, False,  True,  True, False])

## where funksyasi

In [4]:
# where
result = np.where(cond, x_arr, y_arr) #agar shara cond massivda True bolsa x arrayn fals bo'lsa y arrayni mos elementlarni olib yang numpy array qaytaradi
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [5]:
arr = np.random.randn(4, 4) #4 ga 4 o'lchamli taxminiy elementlar
arr 

array([[-0.52833025, -1.02351093, -0.01008862, -0.15230301],
       [ 0.93688601, -0.13616801, -0.76498759, -0.31582689],
       [-1.80350113, -1.17537273,  0.19867857,  0.44509331],
       [-0.04749129, -2.82664336, -0.72536411,  2.12744134]])

In [7]:
#where
resolts = np.where(arr<0, -2, 2) # arrayning manfiy elementlarni -2 ga musbaltarni esa 2ga almashtrish
resolts 

array([[-2, -2, -2, -2],
       [ 2, -2, -2, -2],
       [-2, -2,  2,  2],
       [-2, -2, -2,  2]])

In [8]:
np.where(arr<0, 0, arr)

array([[0.        , 0.        , 0.        , 0.        ],
       [0.93688601, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.19867857, 0.44509331],
       [0.        , 0.        , 0.        , 2.12744134]])