<a href="https://colab.research.google.com/github/SHermukhammadjon/Mohirdev_Data_Science_praktikum/blob/main/matematik_va_statistik_ammallar16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ![Imgur](https://i.imgur.com/5pXzCIu.png)
#\#8.15 Matematik va statistik amallar

In [1]:
import numpy as np

## Statistik metodlar
<img src='https://drive.google.com/uc?id=1H0HMoW5_xT5IuowjtpTjGD9JGLAbDTDY'>

In [7]:
# data
arr = np.random.randn(5, 4) # 5ga 4 o'lchamli taxminy elementlardan tashkil topgan array
arr

array([[-0.17352178,  1.31728761,  0.38041688,  0.72811909],
       [ 0.59103671,  0.21140591,  0.33817306,  0.56691841],
       [ 1.01730818, -2.08579683, -0.36187096,  0.04112   ],
       [-0.12584712, -0.40173316, -0.50246007, -0.72880766],
       [-0.22623026, -1.04606223, -0.48880839, -0.81916829]])

## ***Sum*** metodi

In [9]:
arr.sum() # arrayning barcha elementlarni yig'ndsini qaytaradi

np.float64(-1.768520915662883)

In [10]:
np.sum(arr)

np.float64(-1.768520915662883)

In [11]:
arr.sum(axis=1) # axis 1 bo'ycha harbir listni elementlarni yigndsi

array([ 2.2523018 ,  1.70753408, -1.38923961, -1.75884801, -2.58026917])

In [12]:
arr.sum(axis=0) # ustun bo'ycha yig'ndi

array([ 1.08274572, -2.00489871, -0.63454948, -0.21181846])

## ***mean*** metodi

In [13]:
# sodda ma'lumot
data = np.arange(5) # 0->5gacha tashkil topgan array
data

array([0, 1, 2, 3, 4])

In [14]:
mean = np.sum(data)/len(data)
mean

np.float64(2.0)

In [15]:
# Numpy mean
np.mean(data)


np.float64(2.0)

In [16]:
data.mean()

np.float64(2.0)

In [17]:
arr

array([[-0.17352178,  1.31728761,  0.38041688,  0.72811909],
       [ 0.59103671,  0.21140591,  0.33817306,  0.56691841],
       [ 1.01730818, -2.08579683, -0.36187096,  0.04112   ],
       [-0.12584712, -0.40173316, -0.50246007, -0.72880766],
       [-0.22623026, -1.04606223, -0.48880839, -0.81916829]])

In [18]:
arr.mean() # arrayning barcha o'rtacha  elementlarni qiymati 

np.float64(-0.08842604578314414)

In [19]:
np.mean(arr, axis=1) #Qator bo'ycha o'rtacha qiymatni qaytaradi

array([ 0.56307545,  0.42688352, -0.3473099 , -0.439712  , -0.64506729])

In [20]:
np.mean(arr, axis = 0) #Ustunlar bo'ycha o'rtacha qiymatni qaytaradi

array([ 0.21654914, -0.40097974, -0.1269099 , -0.04236369])

## ***cumsum*** metodi

In [21]:
data

array([0, 1, 2, 3, 4])

In [22]:
data.cumsum() # o'zidan oldin kelgan barcha elementlarni qo'shadi

array([ 0,  1,  3,  6, 10])