<a href="https://colab.research.google.com/github/SHermukhammadjon/Mohirdev_Data_Science_praktikum/blob/main/arithmetic15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ![Imgur](https://i.imgur.com/5pXzCIu.png)
#\#8.15 Arifmetik amallar

In [1]:
import numpy as np

## Ko'pytrish, bo'lish, qo'shish, ayirish va h.k amallar

In [7]:
# data
arr1 = np.arange(6).reshape(2, 3) # )dan -> 6 gacha bo'lgan elementlardan tashkil topgan array
arr2 = np.arange(6, 12).reshape(2, 3) # 2~12 gacha bo'lgan elementlardan tashkil topgan massiv

In [8]:
print(arr1)
print(arr2)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [12]:
#Ko'paytrish
arr1 * arr2 # arr1ni mos elementlarni arr2ni mos elementlariga ko'paytiradi

array([[ 0,  7, 16],
       [27, 40, 55]])

In [16]:
# bo'lish
arr2[1:] / arr1[1:] #Bu esa boladi (0 ni tashlab ketdim)

array([[3. , 2.5, 2.2]])

In [14]:
# Qo'shish
arr1 + arr2

array([[ 6,  8, 10],
       [12, 14, 16]])

In [15]:
#ayirish
arr2 - arr1

array([[6, 6, 6],
       [6, 6, 6]])

In [19]:
# Darajaga oshrish oshrish
arr1**2

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [20]:
arr1*3

array([[ 0,  3,  6],
       [ 9, 12, 15]])

In [21]:
#Kvadrat ildizni topish (sqrt)
arr2**0.5

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])