<a href="https://colab.research.google.com/github/SHermukhammadjon/Mohirdev_Data_Science_praktikum/blob/main/working_with_files18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ![Imgur](https://i.imgur.com/5pXzCIu.png)
# \#8.19 Fayillar bilan ishlash

In [1]:
import numpy as np 

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.save('data', np.arange(10))
arr1 = np.load('data.npy')
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr2 = np.arange(20)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
np.savez('data', a=arr1, b=arr2)

In [18]:
arrayis = np.load('data.npz')
arrayis

NpzFile 'data.npz' with keys: a, b

In [19]:
arrayis['a']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])