# ![Imgur](https://i.imgur.com/5pXzCIu.png)
# \#1 List and array

In [2]:
# ! pip install numpy
import numpy as np 

In [4]:
python_list = list(range(100_000))
numpy_array = np.array(python_list)

In [7]:
python_list[-1]

99999

In [9]:
numpy_array

array([    0,     1,     2, ..., 99997, 99998, 99999], shape=(100000,))

In [11]:
%time  for _ in range(10): [x*2 for x in python_list] #Normal xisoblash

CPU times: total: 31.2 ms
Wall time: 104 ms


In [12]:
%time for _ in range(10): numpy_array*2 # Vektorlashgan xisoblash

CPU times: total: 0 ns
Wall time: 1.11 ms


# \#2 Numpy array

### Massiv yaratish

In [16]:
python_list = [1, 2, 3, 4, 5, 6, 7, 1, 0, -1]
numpy_array = np.array(python_list)

In [17]:
print(type(numpy_array))
print(type(python_list))

<class 'numpy.ndarray'>
<class 'list'>


In [18]:
python_tuple = (1, 2, 3, 4, 5, 6, 7, 1, 0, -1)
numpy_array2 = np.array(python_list)

In [19]:
print(type(numpy_array2))
print(type(python_tuple))

<class 'numpy.ndarray'>
<class 'tuple'>


In [20]:
numpy_array2 

array([ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1])

### Massiv o'lchami

#### 1D array

In [21]:
numpy_array.ndim # array o'lchamni chiqarib beradi

1

In [56]:
numpy_array2.ndim

1

### 2D array

In [22]:
two_dimensional_list = [[1, 2, 3, 4], [5, 6, 7, 8]] #list ichidagi list 2d
array3 = np.array(two_dimensional_list)

In [23]:
array3.ndim

2

### 3D array

In [24]:
three_dimensional_list = [[python_tuple, python_tuple], [python_tuple, python_tuple], [python_tuple, python_tuple]] # 3 o'lchamli list

In [25]:
array4 = np.array(three_dimensional_list) # 3 o'lchamli massiv
array4.ndim 

3

### .shape va .size argumentlari

In [26]:
numpy_array2 

array([ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1])

In [27]:
numpy_array2.shape  # Qator va ustunlar sonini chiqarib beradi

(10,)

In [28]:
array4

array([[[ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1],
        [ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1]],

       [[ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1],
        [ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1]],

       [[ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1],
        [ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1]]])

In [29]:
array4.shape 

(3, 2, 10)

In [30]:
array4.size # Arrayni ichda nechta element borligni qaytaradi

60

## N-o'lcho'vli numpy arraylarni yaratishning boshqa usullari

#### zeros va ones funksyalari yordamida massivlar yaratish

In [31]:
array = np.zeros((2, 4)) # Baracha elementlari 0ga teng (2, 4)
array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [121]:
array = np.ones((2, 4)) # Baracha elementlari 0ga teng (2, 4)
array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [122]:
array = np.arange(4, 20, 2) # 4 dan 20gacha massivga 2 qadam bilan np aray xosil qiladi
array

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [123]:
array = np.arange(20) # 0dan 20gacha qiymatlar qadam bilan
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## Qo'shimcha:

In [132]:
array = np.random.rand(2, 4) # (2, 4) o'lchamli --> elementlar (0 ~ 1) oraliqdagi tqxminiy qiymatlardan tashkil topgan
array

array([[0.91443145, 0.92898777, 0.20062998, 0.23937115],
       [0.85540614, 0.1726851 , 0.99013225, 0.99974548]])

In [38]:
array = np.random.randint(10, size=(2, 4)) #O'lchami 2, 4 va max qiymati 10gacha bo'lgan sonlar
array

array([[5, 2, 0, 5],
       [9, 8, 3, 3]], dtype=int32)