<a href="https://colab.research.google.com/github/SHermukhammadjon/Mohirdev_Data_Science_praktikum/blob/main/NumPy/lesson9/Boolen_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ![Imgur](https://i.imgur.com/5pXzCIu.png)
# \#8.9 Boolen Indekslash

In [3]:
import numpy as np

In [4]:
# Names
names = np.array(['Hasan', 'Husan', 'Mirzabek', 'Eliyor', 'Husan', 'Javohir', 'Elyor'])
names 

array(['Hasan', 'Husan', 'Mirzabek', 'Eliyor', 'Husan', 'Javohir',
       'Elyor'], dtype='<U8')

In [9]:
# data
data = np.random.randn(7, 4)
data

array([[ 0.44960755,  0.67878484,  1.69631115,  0.19536205],
       [-1.32579122,  0.29706654,  0.04237544, -0.64315423],
       [ 1.96707579, -0.44159752,  1.4027406 ,  0.24712587],
       [-0.62267387,  0.33272436,  0.66485015,  0.43777453],
       [-0.54535583, -1.53796866,  0.63700045, -0.36690265],
       [-1.07994845, -0.15061689, -0.10048911,  1.68794784],
       [-0.86172963,  0.441732  , -1.50833612, -0.18838745]])

In [10]:
names == 'Husan'

array([False,  True, False, False,  True, False, False])

In [11]:
data[names == 'Husan']  # Husanga tegishli barcha ma'lumotlarni ajratib olish

array([[-1.32579122,  0.29706654,  0.04237544, -0.64315423],
       [-0.54535583, -1.53796866,  0.63700045, -0.36690265]])

In [12]:
data[names == 'Eliyor']  # Eliyor tegishli barcha ma'lumotlarni ajratib olish

array([[-0.62267387,  0.33272436,  0.66485015,  0.43777453]])

In [13]:
data[names == 'Husan', 2:] # Hasanga tegishli oxirgi ustudagit 2ta istunni ajratib olish

array([[ 0.04237544, -0.64315423],
       [ 0.63700045, -0.36690265]])

In [14]:
data[names != 'Husan', 2:] #Husanda tashqari hamma odamlarning ma'umotlari

array([[ 1.69631115,  0.19536205],
       [ 1.4027406 ,  0.24712587],
       [ 0.66485015,  0.43777453],
       [-0.10048911,  1.68794784],
       [-1.50833612, -0.18838745]])

In [ ]:
data[~(names == 'Husan')] # yuqoridagi cell bilan bir xil natijani beradi

array([[0.71711391, 0.76126307, 0.29080096, 0.45814313],
       [0.1132639 , 0.07892818, 0.63540178, 0.34074485],
       [0.08006617, 0.52855225, 0.76357986, 0.48787945],
       [0.20578582, 0.13888541, 0.98024487, 0.89821955],
       [0.01444612, 0.37829796, 0.9819636 , 0.73016724]])

## \#vazifa
## Datadan araydan 2 ta ismmi ma'lumotlarni ajratib oling

In [15]:
print(names)
print(data)

['Hasan' 'Husan' 'Mirzabek' 'Eliyor' 'Husan' 'Javohir' 'Elyor']
[[ 0.44960755  0.67878484  1.69631115  0.19536205]
 [-1.32579122  0.29706654  0.04237544 -0.64315423]
 [ 1.96707579 -0.44159752  1.4027406   0.24712587]
 [-0.62267387  0.33272436  0.66485015  0.43777453]
 [-0.54535583 -1.53796866  0.63700045 -0.36690265]
 [-1.07994845 -0.15061689 -0.10048911  1.68794784]
 [-0.86172963  0.441732   -1.50833612 -0.18838745]]


In [16]:
mask = (names == 'Hasan') | (names == 'Husan')  # or ==  | == yoki
mask

array([ True,  True, False, False,  True, False, False])

In [ ]:
data[mask]

array([[0.71711391, 0.76126307, 0.29080096, 0.45814313],
       [0.24570515, 0.45938023, 0.55147155, 0.90741936],
       [0.47734707, 0.38807453, 0.38325857, 0.65479627]])

In [ ]:
print(data[data < 0])
data[data < 0] = 0

[-0.52538032 -1.44939186 -0.9606766  -1.54714528 -0.33565941 -1.0639033
 -0.46154527 -0.34253584 -1.18795069 -2.50848049 -0.45341714 -0.30288869
 -0.23037936 -0.98629285]


In [ ]:
data

array([[0.22774024, 0.        , 1.29370588, 0.        ],
       [0.        , 1.15412137, 1.13095992, 0.72052436],
       [0.38801841, 0.25756965, 0.        , 0.        ],
       [1.2444704 , 0.        , 0.        , 0.        ],
       [0.85633228, 2.06317809, 0.        , 0.        ],
       [0.        , 1.0229531 , 0.48998246, 0.        ],
       [0.        , 0.        , 0.72612536, 1.62208579]])