<a href="https://colab.research.google.com/github/SHermukhammadjon/Mohirdev_Data_Science_praktikum/blob/main/unversal_funksyalar12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ![Imgur](https://i.imgur.com/5pXzCIu.png)
#\#8.12 Unversal funksyalar

In [2]:
import numpy as np 

###Unversal funksyalar 2 turga bo'lnad va bulardan birinchisi ***Unary*** yani 1ta argument qabul qiluvchi funksyalardir.

### ***sqrt***, ***square***, ***exp***, ***log***, ***modf***, ***sign***, ***isna*** 

In [43]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## ***sqrt*** massivning harbir elementini kvadrat ildizga  oshruvchi funksya:

In [17]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

## ***square*** Massivning elementlarni kvadratga oshruvchi funksya

In [18]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

## ***exp*** funksyasi arraynin barcha elementlarni eksponesiyalaydi

In [22]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.exp(arr) 

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

### ***log*** massivning harbir logarifmni qaytaradi

In [26]:
np.log(arr[1:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

## ***modf*** bu funksya qoldiq sonlarni butun va qoldiq qismnilarga ajratib beruvchi funksya

In [27]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr1 = np.random.randn(6) # 6ta elementdan iborat taxminiy qiymatlarga ega massiv
arr1

array([ 1.44353566,  0.14900617, -0.01001716,  0.51344274,  1.09937968,
        1.55819847])

In [40]:
qoldiq, butun = np.modf(arr1)

In [41]:
print(butun)
print(qoldiq)

[-0. -1. -0. -1. -1.  0.]
[-0.09106705 -0.2446001  -0.62899749 -0.31447349 -0.17279282  0.44449106]


In [42]:
np.modf(arr1)

(array([-0.09106705, -0.2446001 , -0.62899749, -0.31447349, -0.17279282,
         0.44449106]), array([-0., -1., -0., -1., -1.,  0.]))

## ***sign*** funksyasi massiv elementlari manfiy bo'lsa ***-1*** va aksinvha musbat bo'lsa ***1*** joylab qaytaradi

In [48]:
arr1

array([ 1.44353566,  0.14900617, -0.01001716,  0.51344274,  1.09937968,
        1.55819847])

In [49]:
np.sign(arr1)

array([ 1.,  1., -1.,  1.,  1.,  1.])

## ***isnan*** massivning ichda NaN qiymat bo'lsa ***True*** va aksincha bo'lsa ***False*** qaytaradi

In [51]:
arr1

array([ 1.44353566,  0.14900617, -0.01001716,  0.51344274,  1.09937968,
        1.55819847])

In [52]:
np.isnan(arr1)

array([False, False, False, False, False, False])

In [53]:
arr1[2] = np.NaN
arr1

array([1.44353566, 0.14900617,        nan, 0.51344274, 1.09937968,
       1.55819847])

In [54]:
np.isnan(arr1)

array([False, False,  True, False, False, False])

## Unary funksyalariga missollar:
<img src='https://drive.google.com/uc?id=1vqrg5hdDx3IMhuXJLqYo2dlYkPxYZ2ys'>