<a href="https://colab.research.google.com/github/SHermukhammadjon/Mohirdev_Data_Science_praktikum/blob/main/lesson8_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#\#8.3 Numpy array

In [ ]:
import numpy as np

In [ ]:
data1 = [1, 2, 3, 4, 5, 6, 7, 1, 0, -1]
array1 = np.array(data1)

print(f"data1: {type(data1)}")
print(f"array1: {type(array1)}")

data1: <class 'list'>
array1: <class 'numpy.ndarray'>


In [ ]:
data2 = (1, 2, 3, 4, 5, 6, 7, 1, 0, -1)
array2 = np.array(data1)

print(f"data2: {type(data2)}")
print(f"array2: {type(array2)}")

data2: <class 'tuple'>
array2: <class 'numpy.ndarray'>


In [ ]:
array2 

array([ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1])

### 1D array

In [ ]:
array1.ndim

1

### 2D array

In [ ]:
two_dimensional_list = [[1, 2, 3, 4], [5, 6, 7, 8]] #list ichidagi list: 2D

array3 = np.array(two_dimensional_list)
array3.ndim

2

### 3D array

In [ ]:
data1

[1, 2, 3, 4, 5, 6, 7, 1, 0, -1]

In [ ]:
three_dimensional_list = [[data1, data1], [data1, data1], [data1, data1]] # list ichida 2ta list: 3D

array4 = np.array(three_dimensional_list) # 3 o'lchamli numpy array
array4.ndim

3

### .shape va .size argumentlari

In [ ]:
array2 

array([ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1])

In [ ]:
array2.shape  # Qator va ustunlar sonini chiqarib beradi

(10,)

In [ ]:
array4

array([[[ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1],
        [ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1]],

       [[ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1],
        [ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1]],

       [[ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1],
        [ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1]]])

In [ ]:
array4.shape 

(3, 2, 10)

In [ ]:
array4.size # Arrayni ichda nechta element borligni aytaradi

60

## N-o'lcho'vli numpy arraylarni yaratishning boshqa usullari

#### zeros va ones funksyalari yordamida massivlar yaratish

In [ ]:
array = np.ones((2, 4)) # Baracha elementlari 1ga teng (2, 4)
array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
array = np.zeros([4, 10]) # Baracha elementlari 0ga teng (4, 10)
array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### ***arange*** funksyasi yordamida yaratish

In [41]:
arr6 = np.arange(2, 20, 2)  # 4 dan 20gacha 2 qdam bilan bo'lgan massiv
arr6 

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

### ***random*** modilni **rand**, **randint**, **rand** funksyalari bilan yaratish

In [42]:
arr8 = np.random.rand(3,5) # (3, 5) o'lchamli taminan 0~1 oralig'dagi float sonlar bilan to'ldirlgan array
arr8

array([[0.51231965, 0.70604412, 0.10857222, 0.95582204, 0.65162637],
       [0.59758658, 0.04851498, 0.64263274, 0.43983269, 0.59781411],
       [0.75042864, 0.61415278, 0.27885364, 0.35748661, 0.76699318]])

In [46]:
arr9 = np.random.randint(10, size=(3, 5)) #Max qiymat 10 gacha tasodifiy olchami (3, 5) masiv
arr9 

array([[3, 1, 8, 0, 6],
       [0, 8, 1, 8, 0],
       [6, 7, 3, 6, 2]])

## Qo'shimcha funksyalar

In [ ]:
array

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [48]:
arr10 = np.empty((3, 5))
arr10

array([[2.46323740e-316, 0.00000000e+000, 8.73759451e+183,
        8.88212263e+247, 1.68118618e-152],
       [6.01334515e-154, 2.90435030e-144, 2.13041172e-313,
        2.46180817e-316, 2.42092166e-322],
       [1.92792715e-316, 2.29799181e-316, 1.05135755e-153,
        2.42773503e-154, 8.69555537e-322]])