<a href="https://colab.research.google.com/github/SHermukhammadjon/Mohirdev_Data_Science_praktikum/blob/main/NumPy/8.6/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ![Imgur](https://i.imgur.com/5pXzCIu.png)
#\#8.6 Numpy Data type

In [ ]:
import numpy as np 

<img src = 'https://drive.google.com/uc?id=1aVpkPB9i9JfDHq-hvapLJb8osbMA3ApZ'>

In [ ]:
arr1 = np.array([1, 2, 3], dtype = np.float64) #bu float64 ma'lumot turiga ega masiv
arr1 

array([1., 2., 3.])

In [ ]:
arr2 = np.array([1, 2, 3], dtype = np.int32) # int32 ma'lumot turi
arr2

array([1, 2, 3], dtype=int32)

In [ ]:
arr1.dtype 

dtype('float64')

In [ ]:
arr2.dtype

dtype('int32')

### Bir malumot turidan boshqa malumot turiga o'girish

In [ ]:
arr = np.array([1, 2, 3, 4])
arr.dtype

dtype('int64')

In [ ]:
# astype metodi
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4.])

In [ ]:
float_arr.dtype

dtype('float64')

In [ ]:
arr = np.array([1.2, 1.3, 1.4, 1.5])
arr.dtype

dtype('float64')

In [ ]:
int_arr = arr.astype(np.int64)
int_arr

array([1, 1, 1, 1])

In [ ]:
int_arr.dtype

dtype('int64')