#\#8.2 List and array

In [2]:
import numpy as np 

In [13]:
python_list = list(range(100_000))
numpy_array = np.array(python_list)

In [14]:
python_list[-1]

99999

In [16]:
numpy_array 

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [25]:
%time for _ in range(10): [x*2 for x in python_list] #Normal xisoblash

CPU times: user 76 ms, sys: 14.3 ms, total: 90.3 ms
Wall time: 93.4 ms


In [27]:
%time for _ in range(10): numpy_array*2 # Vektorlashgan xisoblash

CPU times: user 2.64 ms, sys: 0 ns, total: 2.64 ms
Wall time: 3.4 ms


#\#8.3 Numpy array

In [42]:
data1 = [1, 2, 3, 4, 5, 6, 7, 1, 0, -1]
array1 = np.array(data1)

In [43]:
print(type(array1))
print(type(data1))

<class 'numpy.ndarray'>
<class 'list'>


In [44]:
data2 = (1, 2, 3, 4, 5, 6, 7, 1, 0, -1)
array2 = np.array(data1)

In [45]:
print(type(array2))
print(type(data2))

<class 'numpy.ndarray'>
<class 'tuple'>


In [46]:
array2 

array([ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1])

### Massiv o'lchami

### 1D array

In [47]:
array1.ndim

1

In [48]:
array2.ndim

1

In [57]:
two_dimensional_list = [[1, 2, 3, 4], [5, 6, 7, 8]] #list ichidagi list 2d

### 2D array

In [58]:
array3 = np.array(two_dimensional_list)

In [59]:
array3.ndim

2

### 3D array

In [74]:
three_dimensional_list = [[data2, data2], [data2, data2], [data2, data2]] # 3 o'lchamli list

In [75]:
array4 = np.array(three_dimensional_list) # 3 o'lchamli massiv

In [76]:
array4.ndim 

3

### .shape va .size argumentlari

In [79]:
array2 

array([ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1])

In [84]:
array2.shape  # Qator va ustunlar sonini chiqarib beradi

(10,)

In [85]:
array4

array([[[ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1],
        [ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1]],

       [[ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1],
        [ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1]],

       [[ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1],
        [ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1]]])

In [86]:
array4.shape 

(3, 2, 10)

In [88]:
array4.size # Arrayni ichda nechta element borligni aytaradi

60

## N-o'lcho'vli numpy arraylarni yaratishning boshqa usullari

#### zeros va ones funksyalari yordamida massivlar yaratish

In [91]:
array = np.zeros((2, 4)) # Baracha elementlari 0ga teng (2, 4)
array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [92]:
array = np.ones((2, 4)) # Baracha elementlari 0ga teng (2, 4)
array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [93]:
array = np.arange(4, 20, 2) # 4 dan 20gacha massivga 2 qadam bilan np aray xosil qiladi
array

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [95]:
array = np.arange(20) # 0dan 20gacha qiymatlar qadam bilan
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])