#\#8.2 List and array

In [131]:
import numpy as np 

In [97]:
python_list = list(range(100_000))
numpy_array = np.array(python_list)

In [98]:
python_list[-1]

99999

In [99]:
numpy_array 

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [100]:
%time for _ in range(10): [x*2 for x in python_list] #Normal xisoblash

CPU times: user 137 ms, sys: 21.3 ms, total: 158 ms
Wall time: 185 ms


In [101]:
%time for _ in range(10): numpy_array*2 # Vektorlashgan xisoblash

CPU times: user 2.29 ms, sys: 9 µs, total: 2.29 ms
Wall time: 2.2 ms


#\#8.3 Numpy array

In [102]:
data1 = [1, 2, 3, 4, 5, 6, 7, 1, 0, -1]
array1 = np.array(data1)

In [103]:
print(type(array1))
print(type(data1))

<class 'numpy.ndarray'>
<class 'list'>


In [104]:
data2 = (1, 2, 3, 4, 5, 6, 7, 1, 0, -1)
array2 = np.array(data1)

In [105]:
print(type(array2))
print(type(data2))

<class 'numpy.ndarray'>
<class 'tuple'>


In [106]:
array2 

array([ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1])

### Massiv o'lchami

### 1D array

In [107]:
array1.ndim

1

In [108]:
array2.ndim

1

In [109]:
two_dimensional_list = [[1, 2, 3, 4], [5, 6, 7, 8]] #list ichidagi list 2d

### 2D array

In [110]:
array3 = np.array(two_dimensional_list)

In [111]:
array3.ndim

2

### 3D array

In [112]:
three_dimensional_list = [[data2, data2], [data2, data2], [data2, data2]] # 3 o'lchamli list

In [113]:
array4 = np.array(three_dimensional_list) # 3 o'lchamli massiv

In [114]:
array4.ndim 

3

### .shape va .size argumentlari

In [115]:
array2 

array([ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1])

In [116]:
array2.shape  # Qator va ustunlar sonini chiqarib beradi

(10,)

In [117]:
array4

array([[[ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1],
        [ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1]],

       [[ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1],
        [ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1]],

       [[ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1],
        [ 1,  2,  3,  4,  5,  6,  7,  1,  0, -1]]])

In [118]:
array4.shape 

(3, 2, 10)

In [119]:
array4.size # Arrayni ichda nechta element borligni aytaradi

60

## N-o'lcho'vli numpy arraylarni yaratishning boshqa usullari

#### zeros va ones funksyalari yordamida massivlar yaratish

In [120]:
array = np.zeros((2, 4)) # Baracha elementlari 0ga teng (2, 4)
array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [121]:
array = np.ones((2, 4)) # Baracha elementlari 0ga teng (2, 4)
array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [122]:
array = np.arange(4, 20, 2) # 4 dan 20gacha massivga 2 qadam bilan np aray xosil qiladi
array

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [123]:
array = np.arange(20) # 0dan 20gacha qiymatlar qadam bilan
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## Qo'shimcha:

In [132]:
array = np.random.rand(2, 4) # (2, 4) o'lchamli --> elementlar (0 ~ 1) oraliqdagi tqxminiy qiymatlardan tashkil topgan
array

array([[0.91443145, 0.92898777, 0.20062998, 0.23937115],
       [0.85540614, 0.1726851 , 0.99013225, 0.99974548]])

In [133]:
array = np.random.randint(10, size=(2, 4)) #O'lchami 2, 4 va max qiymati 10gacha bo'lgan sonlar
array

array([[3, 1, 8, 7],
       [3, 0, 4, 1]])