<a href="https://colab.research.google.com/github/SHermukhammadjon/Mohirdev_Data_Science_praktikum/blob/main/working_with_files18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ![Imgur](https://i.imgur.com/5pXzCIu.png)
#\#8.19 Fayillar bilan ishlash

In [3]:
import numpy as np 

In [4]:
arr = np.arange(10)
arr 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.save('data', arr)

In [6]:
arr2 = np.load('data.npy')

In [7]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr1 = np.arange(20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
np.savez('arrays', a=arr, b=arr1)

In [14]:
arrayis = np.load('arrays.npz')
arrayis['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arrayis['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
np.savez_compressed('array_comp.npz', kalit=arr, b=arr1) 

In [22]:
compres = np.load('array_comp.npz')

In [23]:
compres['kalit']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
compres['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])